theme: minima
title: Wooooooooooooooooooooooow
author: FcoCarreto
email: l181061027@mulege.tecnm.mx
description: El Sol es una estrella, es decir, un cuerpo celeste que brilla con luz propia. # this means to ignore newlines until "baseurl:"
# social links
twitter_username: FcoCarreto # DO NOT include the @ character, or else the build will fail!
github_username:  FcoCarreto # DO NOT include the @ character, or else the build will fail!
show_excerpts: true # set to false to remove excerpts on the homepage
